from .test_linear import test_linear
from .test_bn import test_bn
from .test_dropout import test_dropout
from .test_activations import test_activations
from .test_sequential import test_sequential
from .test_criterions import test_criterions
from .test_optimizers import test_optimizers
from .test_dataloader import test_dataloader
from .test_conv2d import test_conv2d
from .test_avgPool2d import test_avgPool2d
from .test_Lenet import test_Lenet
from .test_RNNcell import test_RNNcell
from .test_RNN import test_RNN
from .test_LSTMcell import test_LSTMcell
from .test_LSTM import test_LSTM
from .test_GRUcell import test_GRUCell
from .test_GRU import test_GRU
from .test_RNN_Classifier import test_RNN_Classifier